### ISSUE TITLE
Support for redirected pages

### ISSUE THREAD

**Issue by bgschaid** [JeroenDeDauw/SubPageList#2]
Got a complaint from a user that SubPageList does not show sub-pages that redirect to other pages and asked me to install https://www.mediawiki.org/wiki/Extension:ExpensiveSubpageList because that supposedly  can do that. In my desperation I grepped the sources (I don't know sh## about PHP) and replaced the line 
```self::OPT_INCLUDE_REDIRECTS => false,```
in ```SimpleSubPageFinder.php```with
```self::OPT_INCLUDE_REDIRECTS => true,```
and now redirect pages are shown.

Is there a way to set this properly (tried ```|redirects=yes```and similar things but didn't work) which isn't documented or is the option not implemented ... yet. In which case it would be nice if it was

**Comment by Protonotarios** [comment]
I second that. Listing redirects is very useful especially on a user page, where you need to see all pages created by that user (e.g. that started as subpages and then were moved to main namespace).

**Comment by emanspeaks** [comment]
This has been incorporated in v1.4 now.  Recommend closing.
