### ISSUE TITLE
Add support for MWs new extension registration

### ISSUE THREAD

**Issue by JeroenDeDauw** [JeroenDeDauw/SubPageList#22]
This needs to be done in such a way the extension still works with older versions of MW (down to MW 1.23) and continues to work via Composer in the way existing users expect it to.

Some of the features of the extension registration should also not be used:
- Hooks
- autoloading
- SpecialPages, Actions, JobClasses, APIModules

The goal is to get the benefits of the new system, not migrating as much to it as possible.

This one is up for the taking. Help with it is much appreciated.

**Comment by JeroenDeDauw** [comment]
Ping @paladox :)

**Comment by kghbln** [comment]
Done with the 2.0.0 release
