### ISSUE TITLE
SubPageList confused by what the page is, kidsonly=no required

### ISSUE THREAD

**Issue by tbm** [JeroenDeDauw/SubPageList#3]
We recently upgraded MediaWiki and SubPageList.  Unfortunately I don't know if from 1.0 or from an earlier release.

Suddenly, our #subpages page would no longer list any subpages.  The workaround is kidsonly=no.

Investigating a bit, it seems SubPageList gets confused by what the page actually is.

At http://wiki.spdx.org/index.php?title=General_Meeting/Minutes
we have:
{{#subpages:|format=ul|kidsonly=no|pathstyle=none|sort=desc}}
and it displays;
- Minutes
  - 2014-06-05
  - 2014-05-01 

Why is "Minutes" displayed?  It's not a subpage - it's the page itself?  I'm pretty sure this was not displayed in the past.

Does this explain why kidsonly=no is required?  kidsonly=yes will only show "Minutes" and nothing else, but surely the kids of the current page (General_Meeting/Minutes is everything under General_Meeting/Minutes/*)

Note that showpage is not set.  In fact, setting showpage=yes makes no difference.

**Comment by TwoWholeWorms** [comment]
I'm seeing this exact behaviour on MW 1.24 with SPL 1.1.1.

Let's say I have the following page structure:

* Characters
    * Gertrude
    * Methuselah
* Locations
    * London
        * Nightclub
        * Cinema
        * Alleyway
    * Manchester
        * Newsagent

If I add `{{#subpages:page=Locations|showpage=no|kidsonly=yes }}` to `[[Locations]]`, I see the following output:

* London
* Manchester

If I add `{{#subpages:page=Locations/London|showpage=no|kidsonly=yes }}` to `[[Locations/London]]`, I would expect to see the following output

* Nightclub
* Cinema
* Alleyway

However, what I actually see is this:

* Locations
    * London
        * Nightclub
        * Cinema
        * Alleyway

It looks like the extension is always getting the top-level page and calculating the remaining options based on whether the current page is that top-level page or not.

**Comment by epicycles** [comment]
I have the same issue -- just wondering if it will be fixed, or if there is another version of subpage listing that would do the right thing.

assume I have a hierarchy like
namespace:root/one/A/1/a
namespace:root/one/A/1/b
namespace:root/one/A/2/a
namespace:root/one/A/2/b
namespace:root/one/B/1/a, etc.
namespace:root/two/A/1/a, etc.
 etc.

On root/one/A  I do: 
{{#subpages:pathstyle=subpagename}}
and I get:
one
   A
      1

      2

**Comment by JeroenDeDauw** [comment]
Thanks all for providing those helpful reports. I've so far lacked sufficient incentive to fix this, and no one else has provided a patch either. I'll look at it for a bit now.

**Comment by JeroenDeDauw** [comment]
This actually opens up some questions about what behaviour is actually wanted, primarily with regards to parent pages.

Are these usecases for displaying the parents of the page for which subpages are shown? For instance given these pages

* level 0
* level 0/level 1
* level 0/level 1/level 2
* level 0/foo

Should this `{{#subpages:level 0/level 1|some option}}` then be able to display the following?

* level 0
    * level 1
        * level 2

Note that you can't just do `{{#subpages:level 0}}` as that would include the `level 0/foo` page.

Additionally, what about non-existing parent pages of indirect children? These used to not be shown, which was changed by version 1.0. Is that always desired though? Example:

* level 0
* level 0/level 1
* level 0/level 1/level 2/level 3
Right now `{{#subpages:level 0}}` results into

* level 0
    * level 1
        * level 2
            * level 3

Rather than

* level 0
    * level 1
            * level 3

**Comment by JeroenDeDauw** [comment]
I'm now cleaning up the design flaw that led to this bug: TreeListRenderer should just render the pages it gets and not have options such as `OPT_SHOW_TOP_PAGE` and `OPT_MAX_DEPTH`. Altering the pages that should be shown should happen before they are passed to the HierarchyRenderer, and presumably before the SubPageListRenderer as well.

**Comment by irainst0rmed** [comment]
Hi,
I'm having the same issue where : 
`{{#subpages:showpage=no|kidsonly=yes}}`

Only displays the pages it's at instead of it's subpages.

Do we have an ETA ?

Thanks !

Charles

**Comment by pieter-biomerieux** [comment]
I'm having this issue also.

SubPageList version: 1.6.0
MediaWiki version: 1.32.0

I am be willing to create a pull request, but I don't know how to easily test my code.

**Comment by irainst0rmed** [comment]
> I'm having this issue also.
> 
> SubPageList version: 1.6.0
> MediaWiki version: 1.32.0
> 
> I am be willing to create a pull request, but I don't know how to easily test my code.

Hi Pieter,

Since I haven't had any responses since 2017, I used this extension instead to bypass this issue : https://www.mediawiki.org/wiki/Extension:SubPageList3

Hope it helps !

Charles

**Comment by JeroenDeDauw** [comment]
@pieter-biomerieux a PR is most welcome. I can take care of the tests if you fix the issue itself. I had a go at this back in 2015 and the incomplete PR _might_ be of some help to you.

**Comment by MLRodrigue** [comment]
the Hallo Welt! dev team would like to do a PR to fix the `showpage` and `kidsonly` parameters for non-superpages. We would also like to implicitly (or as parameter) support `displayname`.

**Comment by JeroenDeDauw** [comment]
Got for it!

**Comment by MLRodrigue** [comment]
Great, thank you. We will start our internal ticket process.

**Comment by it-spiderman** [comment]
Hello @JeroenDeDauw HalloWelt would like to make a pull request, but my user does not have permission to push to a new feature branch. Could you grant me the permissions or create a feature branch that i can push to? Thanks

**Comment by JeroenDeDauw** [comment]
You have an invite

**Comment by it-spiderman** [comment]
Thank you, i made a pull request

**Comment by JeroenDeDauw** [comment]
Should be fixed by https://github.com/JeroenDeDauw/SubPageList/pull/70

**Comment by it-spiderman** [comment]
@JeroenDeDauw Would you mind releasing a new version (tag) with this fix included? Thanks
