### ISSUE TITLE
Mark v1.4 as stable release

### ISSUE THREAD

**Issue by emanspeaks** [JeroenDeDauw/SubPageList#33]
Are there any showstoppers to marking v1.4 as a stable release?  It is still marked as dev.

**Comment by JeroenDeDauw** [comment]
Thanks for pointing this out. I've created a release PR now. If you could double check I did not forget to update some version number or some silly such thing, that'd be awesome.

**Comment by kghbln** [comment]
We still need a tag though. While we are at it. What happened to 1.3.0? I think this one could still be changed to 1.3.0 since the date needs to be amended in the release notes anyway. Sorry that I did not see this before.

**Comment by JeroenDeDauw** [comment]
There is no 1.3.0. No such version was created for our alien overloads in orbit.
