### ISSUE TITLE
Warning: Parameter 3 to SubPageList\Setup::SubPageList\{closure}() expected to be a reference, value given

### ISSUE THREAD

**Issue by rabin-io** [JeroenDeDauw/SubPageList#35]
After moving a page i got this message,
```
Warning: Parameter 3 to SubPageList\Setup::SubPageList\{closure}() expected to be a reference, value given in /www/mediawiki-1.27.1/includes/Hooks.php on line 195
Move succeeded
```

```
Product       Version
MediaWiki     1.27.1
PHP           7.0.12-1~dotdeb+8.1 (fpm-fcgi)
MySQL         5.5.52-0+deb8u1
ICU           52.1
SubPageList   1.4.0
```

**Comment by kghbln** [comment]
@rabin-io Which versions of MediaWiki, SubPageList and PHP are you using?

**Comment by rabin-io** [comment]
Hello @kghbln , Just updated the first comment with the requested info.

**Comment by kghbln** [comment]
@rabin-io Thanks a bunch. @JeroenDeDauw Ready to be tackled?!

**Comment by JeroenDeDauw** [comment]
This looks to be an error in MediaWiki, which is solved in its latest development version. So either upgrade or downgrade your MW, nothing we can do about this here.

https://github.com/wikimedia/mediawiki/commit/8f15bc8ec9e15bca8c19490ccaa45f805d54a035

**Comment by kghbln** [comment]
@JeroenDeDauw This is a bit strange. The change set you linked is part of the 1.27.1 release so there must be something else in the water probably with MediaWiki.

**Comment by JeroenDeDauw** [comment]
You're right: https://github.com/wikimedia/mediawiki/blob/1.27.1/includes/MovePage.php#L387

So I suppose this warning was caused when @rabin-io his version was not 1.27.1.

**Comment by rabin-io** [comment]
Hello @JeroenDeDauw, 
I do all my documentation in my wiki , and so I keep it up to date - ALL THE TIME.
I came a cross this warning above just today (so it recent), as I do not move/rename pages often.

**Comment by JeroenDeDauw** [comment]
Well, I see no reason why you'd get this warning with MW 1.27.1 and SPL 1.4.0. I did find a bug in MW that would cause such warnings but has been fixed. So not much more I can do here.

**Comment by rabin-io** [comment]
OK you were right, 
so I went and downloaded the gz file for 1.27.1 and reapply it (overwriting everything). And it seems to solve this problem, the above warning won't show any more.

Thank you for the quick reply.
& A great Plugin.

**Comment by kghbln** [comment]
> OK you were right, 

Thanks for your feedback and confirming that everything is ok now.
