### ISSUE TITLE
limit done before sort

### ISSUE THREAD

**Issue by tbm** [JeroenDeDauw/SubPageList#4]
I store meeting minutes in the format Group/Minutes/20YY-MM-DD

I use sort=desc|limit=5 to get the 5 LATEST minute notes.

In the past, this worked just fine, but after an upgrade, this shows the FIRST 5 minutes, not the LAST 5 minutes.

It seems that the limit to 5 is done before the sort as the 5 minutes displayed are properly sorted descending.

You can see the problem in action here: http://wiki.spdx.org/view/General_Meeting/Latest_Minutes

**Comment by stokito** [comment]
Hello, do you have any plans to fix that?

**Comment by JeroenDeDauw** [comment]
I will happily review a fix but am not planning to write one myself at present.

**Comment by charger** [comment]
Fix is ready. Review it, please.

**Comment by JeroenDeDauw** [comment]
Done with https://github.com/JeroenDeDauw/SubPageList/pull/41
