### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by irainst0rmed** [JeroenDeDauw/SubPageList#44]
### Setup

- MediaWiki version: 1.29.1
- PHP version: 5.6.31 (cgi-fcgi)
- Database and version (MySQL etc.): 5.1.73-community
- SubPageList version: 1.5.x

### Issue

Placed the folder SubPageList under Mediawiki\extensions.
Ran `composer install` inside the folder.
Going back to Mediawiki folder and run : 
`composer require mediawiki/sub-page-list "~1.5"`

Getting this : 
```
C:\inetpub\wwwroot\MediaWiki>composer require mediawiki/sub-page-list "~1.5"
./composer.json has been updated
> ComposerHookHandler::onPreUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package justinrainbow/json-schema (installed at 5.2.0, requi
red as ~3.0) is satisfiable by justinrainbow/json-schema[5.2.0] but these confli
ct with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

```

First time installing an extension using composer so basic steps would be appreciated.

Thanks !

Charles :)

**Comment by kghbln** [comment]
Yeah, MediaWiki is currently a bit painful. See [here](https://www.semantic-mediawiki.org/wiki/Help:Installation/Troubleshooting#Your_requirements_could_not_be_resolved_to_an_installable_set_of_packages.) sow the solution should be:

1. `composer update --no-dev`
2. `composer require mediawiki/sub-page-list "~1.5" --update-no-dev`

**Comment by kghbln** [comment]
Besides, your database version is a bit scary. Note that MediaWiki 1.30+ will [no longer support versions](https://www.mediawiki.org/wiki/Compatibility#Database) lower than 5.5+

**Comment by irainst0rmed** [comment]
It worked thank you !

Charles
