### ISSUE TITLE
nested subpages

### ISSUE THREAD

**Issue by dgrimreaper** [JeroenDeDauw/SubPageList#5]
Hi,

I'm trying to get this extension to work with nested subpages and it's not doing what I expect.

Say there's pages A/B1/C1, A/B1/C2, A/B1/C2, A/B2/C2.

Then on page A/B1 if I do {{#subpages:kidsonly=yes}} then it shows only a link to A/B1.  I expected it to show links to A/B1/C1 and A/B1/C2.

{{#subpages:showpage=yes|kidsonly=yes}} on the same page shows links to A and A/B1.  I expected it to show links to A/B1, A/B1/C1 and A/B1/C2.

Is it getting confused between the parent of the tree and the current page, or just my expectations are not right?

What I'd really like to do is say on page A/B1, explicitly put something like {{#subpages:page=A/B1/C1|intro="Something about C1|kidsonly=yes}} and have even more levels of subpages under A/B1/C1/D1 etc.  Then have it display just the kids and nothing about the parents or current page.

Using MW 1.19.1 and subpagelist 1.1.1.

Thanks,
Daniel.

**Comment by TwoWholeWorms** [comment]
Looks like you're experiencing the same problem that @tbm and I are experiencing in issue #3.

**Comment by JeroenDeDauw** [comment]
Ok, closing this one then
