### ISSUE TITLE
SubPageList does not work with cedilla

### ISSUE THREAD

**Issue by LeoShivas** [JeroenDeDauw/SubPageList#53]
### Setup

- MediaWiki version: 1.32.0
- PHP version: 7.3.4
- Database and version (MySQL etc.): MySQL 5.7.30
- SubPageList version: 1.6.1

### Issue

When a subpage contains a "c" character with a cedilla "ç", the subpage is not listed.

### Steps to reproduce the observation
Create a subpage with the "Traçabilité" name.

PHP logs no errors, there is no stack trace.

**Comment by JeroenDeDauw** [comment]
Thanks for reporting the issue!

Possibly there is some encoding issue in the database query that finds the subpages.

**Comment by LeoShivas** [comment]
After somes tests, it appears it is not the cedilla. But the issue is still here.
I'll open a new issue.
