### ISSUE TITLE
Composer gives errors when trying to install this extension

### ISSUE THREAD

**Issue by ruuttt** [JeroenDeDauw/SubPageList#56]
### Setup

- MediaWiki version:1.35.1
- PHP version:7.4.0 
- Database and version (MySQL etc.): MariaDB Version: 10.4.10
- **Composer version: 2.0.9 2021-01-27 16:09:27**
- SubPageList version: 

### Issue

Composer gives errors when trying to install this extension. See screenshot:
<img width="673" alt="composer error" src="https://user-images.githubusercontent.com/3007993/108981409-ff8f1c00-768c-11eb-8035-311d36c3bdf1.png">

Do I need to install an older version of composer?

**Comment by kghbln** [comment]
You need to use version 1.x of Composer. This is a general issue with MediaWiki and not specific to this extension.

**Comment by ruuttt** [comment]
I managed to downgrade composer by running: `composer self-update 1.10.20` and after that I could run `composer require mediawiki/sub-page-list "~1.6"` without errors.
