### ISSUE TITLE
SubPageList-1.1.1 doen't work after wiki's upgrade 

### ISSUE THREAD

**Issue by NatashaBrown** [JeroenDeDauw/SubPageList#6]
We have upgraded wiki - http://wikitranslate.org/wiki/Special:Version Everything works but not SubPageList-1.1.1. When I add it the wiki goes blank.

Betacommand told me on irc yesterday that the extension no longer has support. Is it true? I love the extension and we had it from the day one. I am very upset. Jeroen, please, keep on working on it. We need it!

**Comment by JeroenDeDauw** [comment]
This extension is maintained. Closing this issue as it does not contain information that can be acted upon, such as an error message or stack trace.
