### ISSUE TITLE
SubPageList requires ParserHooks

### ISSUE THREAD

**Issue by chiafa** [JeroenDeDauw/SubPageList#62]
### Setup

- MediaWiki version: 1.35.7
- PHP version: 7.4.3
- Database and version (MySQL etc.): MySQL 8.0.29-0ubuntu0.20.04.3
- SubPageList version: 2.0

### Issue
Hi,
if enable the SubPageList with wfLoadExtension( 'SubPageList' ); it not works and I see on MediaWiki the follow error:

### Backtrace
```
PHP Fatal error:  Uncaught ExtensionDependencyError: SubPageList requires ParserHooks to be installed.
 in /../w/includes/registration/ExtensionRegistry.php:435
Stack trace:
#0 /../w/includes/registration/ExtensionRegistry.php(258): ExtensionRegistry->readFromQueue(Array)
#1 /../w/includes/Setup.php(161): ExtensionRegistry->loadFromQueue()
#2 /../w/maintenance/doMaintenance.php(91): require_once('/var/www/htdocs...')
#3 /../w/maintenance/runJobs.php(129): require_once('/var/www/htdocs...')
#4 {main}
  thrown in /../w/includes/registration/ExtensionRegistry.php on line 435
```

But looking on "Special:Version" page of MediaWiki I see the ParserHooks is installed and the version is 1.6.1.
Thanks for the support!

**Comment by kghbln** [comment]
I can confirm this bug. The reason is that Composer does not install ParserHooks though it should.

**Comment by kghbln** [comment]
@osnard Something must have gone in you pull https://github.com/JeroenDeDauw/SubPageList/commit/17f66feb8e758f5e6dc8fb5c40d645fddd6eeb14 Could you have a peep?

**Comment by osnard** [comment]
Sure, I will check. Sorry for the inconvenience.

**Comment by osnard** [comment]
Okay, I have created a couple of commits to fix this:

Option 1: Convert Extension:ParserHooks to use `extension.json` and disable implicit activation by composer autoloader. This requires a major version release, as it changes the way the extension gets activated. This may be problematic, as this extension is a dependency to other extensions as well (SemanticMediaWiki). It will also require a new release of SPL to match the new versions
- https://github.com/JeroenDeDauw/ParserHooks/pull/25
- https://github.com/JeroenDeDauw/SubPageList/pull/63

Option 2: Convert Extension:ParserHooks to use `extension.json` but keep implicit activation by composer autoloader. This seems like a more b/c change any may not require a major version release
- https://github.com/JeroenDeDauw/ParserHooks/pull/26

Btw. I have noticed the failing tests and will look into them ASAP.

**Comment by osnard** [comment]
Looks like CI tests are failing due to the CI environment rather than due to the change. Any advice is appreciated.

**Comment by chiafa** [comment]
Many thanks for your quickly response! I will patiently wait for your feedback/fix.

**Comment by JeroenDeDauw** [comment]
Ah now I understand why this is failing. It is that this line got added: https://github.com/JeroenDeDauw/SubPageList/blob/master/extension.json#L15

Easiest fix is to just remove that and continue to treat ParserHooks as a PHP library rather than a MediaWiki extension.

**Comment by chiafa** [comment]
I confirm by removing the line in the file extension.json everything works fine. Thanks again!

**Comment by JeroenDeDauw** [comment]
@osnard Thanks for looking into this. Sorry that I did not spot the cause yesterday when looking at this issue briefly, that would have saved you a bunch of work.
